### ISSUE TITLE
You didn;t make this

### ISSUE THREAD

**Issue by monkxy** [Glixh/Game-Hacks#1]
nice code you didnt make

**Comment by Glixh** [comment]
🫥 "Yawn", Sorry I don't have time to deal with haters

**Comment by Glixh** [comment]
This you???

**Comment by monkxy** [comment]
Bro just admit you stole the code lmao, it's not being a hater it's just the fact you didn't make the code. 🙏🤷‍♂️

**Comment by monkxy** [comment]
And it's very clear you took heave inspiration from glixzzy on your name,

**Comment by prndndndndnndnd** [comment]
honestly he is right  he shouldn`t have to  deal with hater`s and close this down
